---
Metrics collection endpoint:
  local:
    broker:
      type: kafka
      host: '127.0.0.1'
      port: 9092
      auth: no_auth

Metrics storage endpoint:
  local:
    # number of seconds between burst-transactions to DB. It's highly recommended that
    # this time is at least 10x larger than request sleep time for paired service - metric collector.env
    # In case it's smaller or comparable, DB publisher service may through warnings in log
    upload every: 60
    db:
      type: postgres
      host: '127.0.0.1'
      port: 5432
      auth: scram
